#!/bin/bash
#
# Striim Cluster Node
#

cd "/opt/striim"

if [[ "$1" == "start" ]]; then
    export NO_DERBY=1
    if [ -f /opt/striim/conf/startUp.properties ]; then
      /opt/striim/bin/createStriimProperties.sh
    fi
    if [ ! -f /opt/striim/conf/log4j.server.properties ]; then
      /opt/striim/bin/createLog4jServerProps.sh
    fi
    export CLASSPATH="/opt/striim/extlib/*"
    echo -e "\n\n\n" | `dirname $0`/../bin/server.sh ${WA_OPTS}
fi
